spring:
  ai:
    google:
      genai:
        api-key: ${GOOGLE_AI_API_KEY}
        chat:
          options:
            model: gemini-3.1-flash-lite
            temperature: 0.2
            top-p: 0.85
            max-output-tokens: 2048
        embedding:
          api-key: ${GOOGLE_AI_API_KEY}
          text:
            model: gemini-embedding-001